# Generated by Django 4.1.9 on 2023-06-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='server_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('model_acc', models.CharField(max_length=255)),
                ('model_loss', models.CharField(max_length=255)),
            ],
        ),
    ]
